name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: running arvan
        run: node .github/scripts/arvan-dns.js
        env:
          DOMAIN: ${{ vars.DOMAIN }}
          ARVAN_API_KEY: ${{ secrets.ARVAN_API_KEY }}
          SERVER_IP: "1.1.1.1"
